#! /bin/sh

sxhkd &
wmname LG3D &
~/.config/polybar/launch.sh &
feh --bg-fill $HOME/img/wallpaper.jpg
# ~/.config/bspwm/scripts/background &
compton --config $HOME/.config/compton/compton.conf &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true